import type { NextPage } from 'next';
import { useWeb3React } from '@web3-react/core';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Swap from '../components/Swap';
import { ChainsTokensToolsProvider } from '../components/providers/chainsTokensToolsProvider';
import ConnectButton from '../components/web3/ConnectButton';
import DisconnectButton from '../components/web3/DisconnectButton';

const Home: NextPage = () => {
  const web3 = useWeb3React();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to example dex!</h1>
        {web3.account?.length ? (
          <>
            <p>{'Connected - ' + web3.account}</p>
            <DisconnectButton />
          </>
        ) : (
          <ConnectButton />
        )}
        <ChainsTokensToolsProvider>
          <Swap />
        </ChainsTokensToolsProvider>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
